### ISSUE TITLE
Team should be allowed to have only one game in round

### ISSUE THREAD

**Issue by NataliiaBidiuk** [VolleyManagement/volley-management#148]
Schedule regular game with a team, and schedule DayOff game with the same team.

Second game should not be allowed in the same round

- [x] #152 Only game or day off in one round for one team

- [x] #151 Testing schedule for 1 round

**Comment by sdiachen** [comment]
@NataliiaBidiuk Are those games in the same round or in different ones?

**Comment by NataliiaBidiuk** [comment]
In one round. But with game everything good, a team can`t play at the same time twice but can have game and day off, if I good understood.
![image](https://user-images.githubusercontent.com/33187342/36251838-4863a544-124b-11e8-87ad-ee6f8ae64383.png)
