### ISSUE TITLE
Fix automatically appearing team in next round in PlayOff

### ISSUE THREAD

**Issue by oleggerus** [VolleyManagement/volley-management#229]
Create new PlayOff tournament. If one of team has two matches on first round - this team automatically appeared on next round.
![image](https://user-images.githubusercontent.com/28676005/37292561-c424354a-2619-11e8-87f9-6f84812b3223.png)

**Comment by YuriiChornyi** [comment]
steps to reproduce 
![image](https://user-images.githubusercontent.com/17709640/38177640-3d65afbc-360d-11e8-807b-842f50df5b4c.png)

**Comment by oleggerus** [comment]
Cannot reproduce again too.
