### ISSUE TITLE
User can edit game in PlayOff schedule.

### ISSUE THREAD

**Issue by Myroslavv** [VolleyManagement/volley-management#260]
If you log in as a user and go to playoff tournament -> schedule, you'll see
![image](https://user-images.githubusercontent.com/11539042/37565243-3e1b9f80-2aae-11e8-83f4-af161df11205.png)
If you try to save your changes - an error occurs
![image](https://user-images.githubusercontent.com/11539042/37565252-5c04bcf2-2aae-11e8-90d2-77363ac67725.png)

**Comment by sdiachen** [comment]
Duplicate of #177
